### ISSUE TITLE
No profile data was found, on Tensorboard

### ISSUE THREAD

**Issue by Anatolist** [tensorflow/profiler#12]
Hi everyone, 
Tensorflow 2.2
TEnsorboard 2.2.1
Ubuntu 16
Python 3.5

I follow the installation guide and I wrote the commands
`$ git clone https://github.com/tensorflow/profiler.git profiler
$ mkdir profile_env
$ python3 profiler/install_and_run.py --envdir=profile_env --logdir=profiler/demo`
where profiler/demo I put my training catalog.

So the command became 
`python3 profiler/install_and_run.py --envdir=profile_env --logdir=training` 
 
I took an error that I think its not from the folder training. (The Tesnorboard running perfect and I took the scalars )

`anatoli@ubuntu:~/tensorflow/tensorflow/models/research/object_detection$ python3 profiler/install_and_run.py --envdir=profile_env --logdir=training
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/bin/python3
Not overwriting existing python script /home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/bin/python (you must use /home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/bin/python3)
Cannot find a wheel for pip
Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "profile_env/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/tensorboard/main.py", line 43, in <module>
    from tensorboard import default
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/tensorboard/default.py", line 34, in <module>
    import pkg_resources
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/anatoli/tensorflow/tensorflow/models/research/object_detection/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
Traceback (most recent call last):
  File "profiler/install_and_run.py", line 58, in <module>
    main()
  File "profiler/install_and_run.py", line 54, in main
    venv.run('tensorboard', '--logdir=' + args.logdir, '--bind_all')
  File "profiler/install_and_run.py", line 40, in run
    run(os.path.join(self.envdir, 'bin', program), *args)
  File "profiler/install_and_run.py", line 29, in run
    subprocess.run(' '.join(args), shell=True, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'profile_env/bin/tensorboard --logdir=training --bind_all' returned non-zero exit status 1
`

Thank U in advanced

**Comment by qiuminxu** [comment]
Hi @Anatolist , thanks for your question. Can you list the log structure in profile_demo ?

**Comment by Anatolist** [comment]
> Hi @Anatolist , thanks for your question. Can you list the log structure in profile_demo ?

When executed the command above I get these errors , nothing more. Is there log somewhere else? Can I get more logs some how?

**Comment by qiuminxu** [comment]
@Anatolist sorry, I meant to say what is inside profile_demo? The profiler looks for specific files and folder directories for profile data. It is possible the files you moved into profile demo is in a different structure.

**Comment by Anatolist** [comment]
In the training folder, there are :
![image](https://user-images.githubusercontent.com/57349790/80643468-08f52b00-8a60-11ea-95b7-5b2749643ff4.png)

and I run the 
`tensorboard --bind_all --port 6006 --logdir=training` so I run an instance of tensorboard where I see the results of training. 
After I follow the installation guide of profiler with command 
`python3 profiler/install_and_run.py --envdir=profile_env --logdir=profiler/demo` and I get the errors.

You said the profiles looks for specific files and folder directories, Is there any manual or docs to read about and I understand how can I run the profiler installation?

Thank u for your time

**Comment by qiuminxu** [comment]
From the screenshot, it seems that you don't have a profile collected.
We are looking for a plugin/profile sub directory and a .profile-empty event file for index.

An example is this:
<img width="1098" alt="Screen Shot 2020-04-29 at 1 59 35 PM" src="https://user-images.githubusercontent.com/3082188/80646530-c1e84500-8a21-11ea-9905-da26996ef9c2.png">


Here's a GPU Profiling Guide: https://tensorflow.org/guide/profiler
and Colab tutorial: https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras

**Comment by Anatolist** [comment]
Hi, So I did it again from the beginning. Now I have the record in directories.
![image](https://user-images.githubusercontent.com/57349790/80729384-1e219680-8b00-11ea-8767-b2b2c8be0044.png)

But when I still run the 
`python3 profiler/install_and_run.py --envdir=profile_env --logdir=profiler/demo`
 I get the same error. 


`anatoli@ubuntu:~$ python3 profiler/install_and_run.py --envdir=profile_env --logdir=profiler/demo
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/anatoli/profile_env/bin/python3
Not overwriting existing python script /home/anatoli/profile_env/bin/python (you must use /home/anatoli/profile_env/bin/python3)
Cannot find a wheel for pip
Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "profile_env/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/tensorboard/main.py", line 43, in <module>
    from tensorboard import default
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/tensorboard/default.py", line 34, in <module>
    import pkg_resources
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/anatoli/profile_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
Traceback (most recent call last):
  File "profiler/install_and_run.py", line 58, in <module>
    main()
  File "profiler/install_and_run.py", line 54, in main
    venv.run('tensorboard', '--logdir=' + args.logdir, '--bind_all')
  File "profiler/install_and_run.py", line 40, in run
    run(os.path.join(self.envdir, 'bin', program), *args)
  File "profiler/install_and_run.py", line 29, in run
    subprocess.run(' '.join(args), shell=True, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'profile_env/bin/tensorboard --logdir=profiler/demo --bind_all' returned non-zero exit status 1


I read for these commands, I did it, but it broke my installation, so it is not safe.

`!pip uninstall -y -q tensorflow tensorboard
!pip uninstall -y -q tensorflow tensorboard
!pip install -U -q tf-nightly tb-nightly tensorboard_plugin_profile
`

**Comment by qiuminxu** [comment]
It seems you have a broken pip installation, here's a related github issue:
https://github.com/googleapis/google-cloud-python/issues/2990

**Comment by Anatolist** [comment]
I run the pip3 install --upgrade setuptools and I got:

`anatoli@ubuntu:~$` sudo pip3 install --upgrade setuptools
Requirement already up-to-date: setuptools in ./.local/lib/python3.5/site-packages (46.1.3)`

Uninstall and install them again, but nothing.

That, I noticed in the error is at the beginning that I believe that something is conflicted:

`anatoli@ubuntu:~$ sudo python3 profiler/install_and_run.py --envdir=profile_env --logdir=profiler/demo`

`Already using interpreter /usr/bin/python3`
`Using base prefix '/usr'`
`New python executable in /home/anatoli/profile_env/bin/python3`
`Not overwriting existing python script /home/anatoli/profile_env/bin/python (you must use /home/anatoli/profile_env/bin/python3)`

Because of I did 
`anatoli@ubuntu:/$ pip uninstall setuptools -y && pip install setuptools
Found existing installation: setuptools 46.1.3
Uninstalling setuptools-46.1.3:
 Successfully uninstalled setuptools-46.1.3
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (20.7.0)`
I uninstall that and install the 46.1.3 

But How can I upgrade the setuptools into the folder  /home/anatoli/profile_env/bin/python3 that seems corrupted?

**Comment by qiuminxu** [comment]
How about you run `source profile_env/bin/activate` to activate the virtual_env and then 
`pip3 install --upgrade setuptools`?

I think this is a general pypi issue, not specific to the install_and_run.py script you run. It should also occur when you install other packages. 

You might want to try out other solutions in:
https://github.com/pypa/pip/issues/4216
https://stackoverflow.com/questions/47955397/pip3-error-namespacepath-object-has-no-attribute-sort

**Comment by Anatolist** [comment]
Hi, I  did it, but I have to say that for the starting of tensorboard you do not run the command, I realize that it is for setup only. 
`python3 profiler/install_and_run.py --envdir=profile_env --logdir=profiler/demo` because it goes and overwrites some fixed files like __init__.py.

So the command to start Tensorboard profiler is: 
` tensorboard --bind_all --port 6006 --logdir=profiler/demo` where its not mentioned here:
https://github.com/tensorflow/profiler/. 

@qiuminxu Thank U for your time and help

**Comment by Andrei2Moraru** [comment]
> I'm facing the "No profile data was found" error. ![image](https://user-images.githubusercontent.com/87942974/257161282-8f23f919-a35c-4b26-908d-87bd2af13c7f.png) Can anyone help?

Also facing the same problem

**Comment by GoldenGoldy** [comment]
Downgrading tensorboard-plugin-profile to version 2.8.0 solved the issue for me. 
`pip install tensorboard-plugin-profile==2.8.0`
Found this solution here: https://github.com/tensorflow/profiler/issues/380#issuecomment-1416390693

**Comment by Andrei2Moraru** [comment]
I confirm that @GoldenGoldy's answer was the solution to my problem as well. The profiler's version should match that of the `tensorboard` and `tensorflow` itself ideally. May want to check with something like:

`pip freeze | grep tensor`
