### ISSUE TITLE
TypeError: None has type NoneType, but expected one of: bytes, unicode

### ISSUE THREAD

**Issue by mkuchnik** [tensorflow/profiler#161]
GRPC resolution is `None` using Tensorboard 2.3 on GCP Debian 4.19.118-2+deb10u1 (2020-06-07). This occurs when switching to Profile view. The issue happens sporadically, usually after keeping Tensorboard open for a while.

The [current code](https://github.com/tensorflow/profiler/blob/b4ce1b9c3fbb870b4db8f10d63e9d66027efc9e9/plugin/tensorboard_plugin_profile/profile_plugin.py#L424) seems to be different, so maybe the issue does not exist on nightly.

Trace below (note lines may be off by 1 as I inserted some debug code):
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/backend/application.py", line 526, in __call__                                                                                                  
    return self._app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/backend/application.py", line 567, in wrapper                                                                                                   
    return wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/backend/security_validator.py", line 82, in __call__                                                                                            
    return self._application(environ, start_response_proxy)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/backend/path_prefix.py", line 71, in __call__                                                                                                   
    return self._application(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/backend/experiment_id.py", line 76, in __call__                                                                                                 
    return self._application(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/backend/empty_path_redirect.py", line 47, in __call__                                                                                           
    return self._application(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/backend/application.py", line 590, in wrapper                                                                                                   
    return wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/backend/application.py", line 549, in _route_request                                                                                            
    return self.exact_routes[clean_path](environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/wrappers/base_request.py", line 238, in application                                                                                                
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python3.7/dist-packages/tensorboard_plugin_profile/profile_plugin.py", line 455, in data_route                                                                                      
    data, content_encoding = self.data_impl(request)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard_plugin_profile/profile_plugin.py", line 403, in data_impl                                                                                       
    grpc_request.parameters['resolution'] = request.args.get('resolution')
```

**Comment by qiuminxu** [comment]
Sorry for the late reply. Yes, we have fixed the issue in https://github.com/tensorflow/profiler/commit/870774a72963c6f30f801da75a151b8a1681f6c1 and it should work in tf-nightly.
