### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v1.profiler' has no attribute 'experimental'

### ISSUE THREAD

**Issue by dbl001** [tensorflow/profiler#350]
I'm trying to profile a model with tensorflow 2.5
Here's the error message:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3,
AttributeError: module 'tensorflow.compat.v1.profiler' has no attribute 'experimental'

```
Here's my Anaconda 3.85 environment:
```
% conda list tensorflow
# packages in environment at /Users/davidlaxer/anaconda3/envs/ai:
#
# Name                    Version                   Build  Channel
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-datasets       4.3.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-metadata       1.0.0                    pypi_0    pypi
tensorflow-probability    0.13.0rc0                pypi_0    pypi
tensorflow-text           2.5.0                    pypi_0    pypi
```
```
import tensorflow as tf
import numpy as np
from utils import *
from VDSH import *

tf.compat.v1.enable_v2_behavior()
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()

options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3,
                                                   python_tracer_level = 1,
                                                   device_tracer_level = 1)
tf.profiler.experimental.start('~/logdir', options=options)
# train the model ...
tf.profiler.experimental.stop()
```
Is this the wrong API for tensorflow profiling?

**Comment by dmmolitor** [comment]
It seems that the error message occurred with the [TF 1 version profiler](https://www.tensorflow.org/api_docs/python/tf/compat/v1/profiler/Profiler) (`AttributeError: module 'tensorflow.compat.v1.profiler' has no attribute 'experimental`), while the example code provided uses the TF 2 profiler. 

I was unable to reproduce the error with the example code given in TF 2.7.

The following executed and did not produce the error:
```
import tensorflow as tf

tf.compat.v1.enable_v2_behavior()
tf.compat.v1.disable_eager_execution()

options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3,
                                                   python_tracer_level = 1,
                                                   device_tracer_level = 1)
tf.profiler.experimental.start('~/logdir', options=options)
# train the model ...
tf.profiler.experimental.stop()
```
Is the code sample provided above the code that produced the error you were seeing?

**Comment by dbl001** [comment]
Conda's latest version of tensorflow is 2.5.  Pip is 2.6.
I can't build tensorflow from source on Big Sur.
(e.g. 
AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_11_3_x86_64')
 )
How did you get tensorflow 2.7?

**Comment by dmmolitor** [comment]
Via [tf-nightly](https://pypi.org/project/tf-nightly/).

Were you able to reproduce the error with the example code you provided with TF 2.5?

**Comment by dbl001** [comment]
Yes.
```
(ai) davidlaxer@x86_64-apple-darwin13 VariationalDeepSemanticHashing % python test.py 
WARNING:tensorflow:From /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3, python_tracer_level = 1, device_tracer_level = 1)
AttributeError: module 'tensorflow.compat.v1.profiler' has no attribute 'experimental'
(ai) davidlaxer@x86_64-apple-darwin13 VariationalDeepSemanticHashing % conda list tensorflow
# packages in environment at /Users/davidlaxer/anaconda3/envs/ai:
#
# Name                    Version                   Build  Channel
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-datasets       4.3.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-metadata       1.0.0                    pypi_0    pypi
tensorflow-probability    0.13.0rc0                pypi_0    pypi
tensorflow-text           2.5.0                    pypi_0    pypi
(ai) davidlaxer@x86_64-apple-darwin13 VariationalDeepSemanticHashing % cat test.py
from __future__ import print_function

import tensorflow as tf
import numpy as np
from utils import *
from VDSH import *

tf.compat.v1.enable_v2_behavior()
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()

#gpu_devices = tf.config.experimental.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(gpu_devices[0], True)
options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3, python_tracer_level = 1, device_tracer_level = 1)
tf.profiler.experimental.start('~/logdir', options=options)

filename = 'dataset/ng20.tfidf.mat'
data = Load_Dataset(filename)

latent_dim = 32
sess = get_session("0", 0.50) # choose the GPU and how much memory in percentage that we need
model = VDSH(sess, latent_dim, data.n_feas)

# create an optimizer
learning_rate = 0.001
decay_rate = 0.96
# decay_step = 10000
step = tf.Variable(0, trainable=False)

lr = tf.train.exponential_decay(learning_rate,
                                step,
                                10000,
                                decay_rate,
                                staircase=True, name="lr")

my_optimizer = tf.train.AdamOptimizer(learning_rate=lr) \
    .minimize(model.cost, global_step=step)

init = tf.global_variables_initializer()
model.sess.run(init)
#merged = tf.summary.merge_all()
#model.merged = merged

total_epoch = 20
kl_weight = 0.
kl_inc = 1 / 5000. # set the annealing rate for KL loss

#saver = tf.train.Saver()
#writer = tf.summary.FileWriter("~/logdir/ + '/', graph=model.sess.graph")

for epoch in range(total_epoch):
    epoch_loss = []
    for i in range(len(data.train)):
        # get doc
        doc = data.train[i]
        word_indice = np.where(doc > 0)[0]

        # indices
        opt, loss = model.sess.run((my_optimizer, model.cost),
                                    feed_dict={model.input_bow: doc.reshape((-1, data.n_feas)),
                                               model.input_bow_idx: word_indice,
                                               model.kl_weight: kl_weight,
                                               model.keep_prob: 0.9})


        kl_weight = min(kl_weight + kl_inc, 1.0)
        epoch_loss.append(loss)


        if i % 50 == 0:
            print("\rEpoch:{}/{} {}/{}: Loss:{:.3f} AvgLoss:{:.3f}"
                  .format(epoch+1, total_epoch, i, len(data.train), loss, np.mean(epoch_loss)), end='')
            #print(tf.config.experimental.get_memory_info('GPU:0'))

        # Tensorboard Statistics
            #merged = model.sess.run([model.merged])
            #writer.add_summary(merged, step)
            #writer.flush()
            #writer.close()
            #save_path = savers.save(model.sess, "~/logdir"+ 'model.chkpt')
            #writer = tf.summary.FileWriter('~/logdir' + '/', graph=model.sess.graph)

    # Tensorboard Statistics
        #merged = model.sess.run([model.merged])
        #writer.add_summary(merged, step)
        #writer.flush()
        #writer.close()
        #save_path = savers.save(model.sess, "~/logdir"+ 'model.chkpt')
        #writer = tf.summary.FileWriter('~/logdir' + '/', graph=model.sess.graph)

tf.profiler.experimental.stop()

# run experiment here
zTrain = model.transform(data.train)
zTest = model.transform(data.test)
zTrain = np.array(zTrain)
zTest = np.array(zTest)
medHash = MedianHashing()
cbTrain = medHash.fit_transform(zTrain)


```

**Comment by dmmolitor** [comment]
Using the [documentation](https://www.tensorflow.org/api_docs/python/tf/compat/v1/profiler/Profiler) for the TF 1 profiler may resolve your issue as it seems that is the profiler version shown in the error. To double check this print 
`dir(tf.profiler)`, which based on the error you are seeing should be in line with the TF 1 compatible profiler instead of TF 2.

**Comment by dbl001** [comment]
importing the vdsh package is causing this issue:
E.g.
```
from VDSH import *
```
Without vdsh:
```
% ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow as tf
   ...: import numpy as np

In [2]: options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3
   ...: , python_tracer_level = 1, device_tracer_level = 1)
   ...: tf.profiler.experimental.start('~/logdir', options=options)
2021-08-30 19:23:30.860453: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
2021-08-30 19:23:30.860466: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.

In [3]: print(tf.profiler)
<module 'tensorflow._api.v2.profiler' from '/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/tensorflow/_api/v2/profiler/__init__.py'>

In [4]: dir(tf.profiler)
Out[4]: 
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'experimental']

```
With vdsh:
```
g % ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow as tf
   ...: import numpy as np
   ...: from utils import *
   ...: from VDSH import *
   ...: 
   ...: tf.compat.v1.enable_v2_behavior()
   ...: from tensorflow.python.framework.ops import disable_eager_execution
   ...: disable_eager_execution()
   ...: 
   ...: #gpu_devices = tf.config.experimental.list_physical_devices('GPU')
   ...: #tf.config.experimental.set_memory_growth(gpu_devices[0], True)
   ...: options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3
   ...: , python_tracer_level = 1, device_tracer_level = 1)
WARNING:tensorflow:From /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d902bd215ab6> in <module>
     10 #gpu_devices = tf.config.experimental.list_physical_devices('GPU')
     11 #tf.config.experimental.set_memory_growth(gpu_devices[0], True)
---> 12 options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3, python_tracer_level = 1, device_tracer_level = 1)

AttributeError: module 'tensorflow.compat.v1.profiler' has no attribute 'experimental'

In [2]: dir(tf.profiler)
Out[2]: 
['AdviceProto',
 'GraphNodeProto',
 'MultiGraphNodeProto',
 'OpLogProto',
 'ProfileOptionBuilder',
 'Profiler',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'advise',
 'profile',
 'write_op_log']

In [3]: print(tf.__version__)
2.5.0

```
Investigating ...

**Comment by dbl001** [comment]
This was created as a tensorflow 1.0 project.  In my 'utils.py' this was the problem:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
When I converted all the v1 functions and ran the model, I got this:
```
tensorflow.profiler.XSpace exceeded maximum protobuf size of 2GB: 11649589782
```
Any way around this?

**Comment by dmmolitor** [comment]
You can trace a smaller amount of data to reduce the protobuf size in a number of ways. For example, reduce the number of iterations, the amount of computation between start and stop, or adjust the trace levels via the [profiler options](https://www.tensorflow.org/api_docs/python/tf/profiler/experimental/ProfilerOptions).
