### ISSUE TITLE
When running install_and_run.py , venv uninstall tensorboard and tensorflow

### ISSUE THREAD

**Issue by liuyongheng123** [tensorflow/profiler#61]
In install_and_run.py, there are two codes below:
venv.run('pip3', 'uninstall', '-q', '-y', 'tensorboard')
venv.run('pip3', 'uninstall', '-q', '-y', 'tensorflow')

I think it should have to uninstall the tensorboard and tensorflow in the virtual envirement and then can use profiler to monitor the performance  of the training. But the tensorboard and tensorflow in the virtual envirement is mapping from the original environment into  the venv . So it could not uninstall the tensorboard and tensorflow in venv. It is reported the error like this:

`Traceback (most recent call last):
  File "profile_dev/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/root/profile_dev/lib/python3.5/site-packages/tensorboard/main.py", line 75, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/root/profile_dev/lib/python3.5/site-packages/tensorboard/program.py", line 290, in main
    return runner(self.flags) or 0
  File "/root/profile_dev/lib/python3.5/site-packages/tensorboard/program.py", line 306, in _run_serve_subcommand
    server = self._make_server()
  File "/root/profile_dev/lib/python3.5/site-packages/tensorboard/program.py", line 416, in _make_server
    ingester.deprecated_multiplexer,
  File "/root/profile_dev/lib/python3.5/site-packages/tensorboard/backend/application.py", line 129, in TensorBoardWSGIApp
    tbplugins, flags.path_prefix, data_provider, experimental_plugins
  File "/root/profile_dev/lib/python3.5/site-packages/tensorboard/backend/application.py", line 226, in __init__
    "Duplicate plugins for name %s" % plugin.plugin_name
ValueError: Duplicate plugins for name projector
Traceback (most recent call last):
  File "profiler/install_and_run.py", line 58, in <module>
    main()
  File "profiler/install_and_run.py", line 54, in main
    venv.run('tensorboard', '--logdir=' + args.logdir, '--bind_all')
  File "profiler/install_and_run.py", line 40, in run
    run(os.path.join(self.envdir, 'bin', program), *args)
  File "profiler/install_and_run.py", line 29, in run
    subprocess.run(' '.join(args), shell=True, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'profile_dev/bin/tensorboard --logdir=profile/demo --bind_all' returned non-zero exit status 1`

How can  I install profiler correctly？

**Comment by qiuminxu** [comment]
@liuyongheng123 Can you check out the latest repo and try again?
